export const areaCode = [{
  'letter': 'A',
  'data': [{
    'country': '阿富汗',
    'numCode': '+93'
  }, {
    'country': '阿尔巴尼亚',
    'numCode': '+355'
  }, {
    'country': '阿尔及利亚',
    'numCode': '+213'
  }, {
    'country': '安道尔共和国',
    'numCode': '+376'
  }, {
    'country': '安哥拉',
    'numCode': '+244'
  }, {
    'country': '安圭拉岛',
    'numCode': '+1264'
  }, {
    'country': '安提瓜和巴布达',
    'numCode': '+1268'
  }, {
    'country': '阿根廷',
    'numCode': '+54'
  }, {
    'country': '阿鲁巴',
    'numCode': '+297'
  }, {
    'country': '澳大利亚',
    'numCode': '+61'
  }, {
    'country': '奥地利',
    'numCode': '+43'
  }, {
    'country': '阿塞拜疆',
    'numCode': '+994'
  }, {
    'country': '埃及',
    'numCode': '+20'
  }, {
    'country': '爱沙尼亚',
    'numCode': '+372'
  }, {
    'country': '埃塞俄比亚',
    'numCode': '+251'
  }, {
    'country': '爱尔兰',
    'numCode': '+353'
  }, {
    'country': '澳门地区',
    'numCode': '+853'
  }, {
    'country': '阿曼',
    'numCode': '+968'
  }, {
    'country': '阿拉伯联合酋长国',
    'numCode': '+971'
  }, {
    'country': '阿布哈兹',
    'numCode': '+7'
  }]
}, {
  'letter': 'B',
  'data': [{
    'country': '巴哈马',
    'numCode': '+1242'
  }, {
    'country': '巴林',
    'numCode': '+973'
  }, {
    'country': '巴巴多斯',
    'numCode': '+1246'
  }, {
    'country': '白俄罗斯',
    'numCode': '+375'
  }, {
    'country': '比利时',
    'numCode': '+32'
  }, {
    'country': '伯利兹城',
    'numCode': '+501'
  }, {
    'country': '贝宁',
    'numCode': '+229'
  }, {
    'country': '百慕大',
    'numCode': '+1441'
  }, {
    'country': '不丹',
    'numCode': '+975'
  }, {
    'country': '玻利维亚',
    'numCode': '+591'
  }, {
    'country': '波斯尼亚和黑塞哥维那',
    'numCode': '+387'
  }, {
    'country': '博茨瓦纳',
    'numCode': '+267'
  }, {
    'country': '巴西',
    'numCode': '+55'
  }, {
    'country': '保加利亚',
    'numCode': '+359'
  }, {
    'country': '布基纳法索',
    'numCode': '+226'
  }, {
    'country': '布隆迪',
    'numCode': '+257'
  }, {
    'country': '佛得角',
    'numCode': '+238'
  }, {
    'country': '冰岛',
    'numCode': '+354'
  }, {
    'country': '北马里亚纳群岛',
    'numCode': '+1670'
  }, {
    'country': '巴基斯坦',
    'numCode': '+92'
  }, {
    'country': '帛琉',
    'numCode': '+680'
  }, {
    'country': '巴勒斯坦',
    'numCode': '+970'
  }, {
    'country': '巴拿马',
    'numCode': '+507'
  }, {
    'country': '巴布亚新几内亚',
    'numCode': '+675'
  }, {
    'country': '巴拉圭',
    'numCode': '+595'
  }, {
    'country': '波兰',
    'numCode': '+48'
  }, {
    'country': '波多黎各',
    'numCode': '+1787'
  }]
}, {
  'letter': 'C',
  'data': [{
    'country': "Cote D'Ivoire",
    'numCode': '+225'
  }, {
    'country': '赤道几内亚',
    'numCode': '+240'
  }]
}, {
  'letter': 'D',
  'data': [{
    'country': '丹麦',
    'numCode': '+45'
  }, {
    'country': '多米尼克国',
    'numCode': '+1767'
  }, {
    'country': '东帝汶',
    'numCode': '+670'
  }, {
    'country': '德国',
    'numCode': '+49'
  }, {
    'country': '多哥',
    'numCode': '+228'
  }]
}, {
  'letter': 'E',
  'data': [{
    'country': '厄瓜多尔',
    'numCode': '+593'
  }, {
    'country': '厄立特里亚国',
    'numCode': '+291'
  }, {
    'country': '俄罗斯联邦',
    'numCode': '+7'
  }]
}, {
  'letter': 'F',
  'data': [{
    'country': '福克兰群岛',
    'numCode': '+5'
  }, {
    'country': '法罗群岛',
    'numCode': '+298'
  }, {
    'country': '斐济',
    'numCode': '+679'
  }, {
    'country': '芬兰',
    'numCode': '+358'
  }, {
    'country': '法国',
    'numCode': '+33'
  }, {
    'country': '法国大都会',
    'numCode': '+33'
  }, {
    'country': '法属圭亚那',
    'numCode': '+594'
  }, {
    'country': '法属玻里尼西亚',
    'numCode': '+689'
  }, {
    'country': '菲律宾共和国',
    'numCode': '+63'
  }, {
    'country': '梵蒂冈(罗马教廷)',
    'numCode': '+39'
  }]
}, {
  'letter': 'G',
  'data': [{
    'country': '哥伦比亚',
    'numCode': '+57'
  }, {
    'country': '刚果',
    'numCode': '+242'
  }, {
    'country': '刚果民主共和国',
    'numCode': '+243'
  }, {
    'country': '哥斯达黎加',
    'numCode': '+506'
  }, {
    'country': '古巴',
    'numCode': '+53'
  }, {
    'country': ' 冈比亚',
    'numCode': '+220'
  }, {
    'country': '格鲁吉亚',
    'numCode': '+995'
  }, {
    'country': '格陵兰',
    'numCode': '+45'
  }, {
    'country': '格林纳达',
    'numCode': '+1473'
  }, {
    'country': '瓜德罗普岛',
    'numCode': '+590'
  }, {
    'country': '关岛',
    'numCode': '+1671'
  }, {
    'country': '圭亚那',
    'numCode': '+592'
  }]
}, {
  'letter': 'H',
  'data': [{
    'country': '海地',
    'numCode': '+509'
  }, {
    'country': '洪都拉斯',
    'numCode': '+504'
  }, {
    'country': '哈萨克',
    'numCode': '+7'
  }, {
    'country': '黑山共和国',
    'numCode': '+382'
  }, {
    'country': '荷兰',
    'numCode': '+31'
  }, {
    'country': '荷兰安的列斯群岛',
    'numCode': '+599'
  }, {
    'country': '韩国',
    'numCode': '+82'
  }]
}, {
  'letter': 'J',
  'data': [{
    'country': '柬埔寨',
    'numCode': '+855'
  }, {
    'country': '加拿大',
    'numCode': '+1'
  }, {
    'country': '捷克',
    'numCode': '+420'
  }, {
    'country': '吉布提',
    'numCode': '+253'
  }, {
    'country': '加蓬',
    'numCode': '+241'
  }, {
    'country': '加纳',
    'numCode': '+233'
  }, {
    'country': '几内亚',
    'numCode': '+224'
  }, {
    'country': '几内亚比绍',
    'numCode': '+245'
  }, {
    'country': '吉尔吉斯',
    'numCode': '+996'
  }, {
    'country': '津巴布韦',
    'numCode': '+263'
  }]
}, {
  'letter': 'K',
  'data': [{
    'country': '喀麦隆',
    'numCode': '+237'
  }, {
    'country': '开曼群岛',
    'numCode': '+1345'
  }, {
    'country': '科科斯群岛',
    'numCode': '+61'
  }, {
    'country': '科摩罗',
    'numCode': '+269'
  }, {
    'country': '库克群岛',
    'numCode': '+682'
  }, {
    'country': '克罗地亚',
    'numCode': '+385'
  }, {
    'country': '肯尼亚',
    'numCode': '+254'
  }, {
    'country': '科威特',
    'numCode': '+965'
  }]
}, {
  'letter': 'L',
  'data': [{
    'country': '拉脱维亚',
    'numCode': '+371'
  }, {
    'country': '黎巴嫩',
    'numCode': '+961'
  }, {
    'country': '莱索托',
    'numCode': '+266'
  }, {
    'country': '利比里亚',
    'numCode': '+231'
  }, {
    'country': '利比亚',
    'numCode': '+218'
  }, {
    'country': '列支敦士登',
    'numCode': '+423'
  }, {
    'country': '立陶宛',
    'numCode': '+370'
  }, {
    'country': '卢森堡',
    'numCode': '+352'
  }, {
    'country': '留尼汪岛',
    'numCode': '+262'
  }, {
    'country': '罗马尼亚',
    'numCode': '+40'
  }, {
    'country': '卢旺达',
    'numCode': '+250'
  }, {
    'country': '老挝',
    'numCode': '+856'
  }]
}, {
  'letter': 'M',
  'data': [{
    'country': '孟加拉国',
    'numCode': '+880'
  }, {
    'country': '马达加斯加',
    'numCode': '+261'
  }, {
    'country': '马拉维',
    'numCode': '+265'
  }, {
    'country': '马来西亚',
    'numCode': '+60'
  }, {
    'country': '马尔代夫',
    'numCode': '+960'
  }, {
    'country': '马里',
    'numCode': '+223'
  }, {
    'country': '马尔他',
    'numCode': '+356'
  }, {
    'country': '马绍尔群岛',
    'numCode': '+692'
  }, {
    'country': '马提尼克岛',
    'numCode': '+596'
  }, {
    'country': '毛里塔尼亚',
    'numCode': '+222'
  }, {
    'country': '毛里求斯',
    'numCode': '+230'
  }, {
    'country': '马约特',
    'numCode': '+262'
  }, {
    'country': '墨西哥',
    'numCode': '+52'
  }, {
    'country': '密克罗尼西亚',
    'numCode': '+691'
  }, {
    'country': '摩尔多瓦',
    'numCode': '+373'
  }, {
    'country': '摩纳哥',
    'numCode': '+377'
  }, {
    'country': '蒙特塞拉特',
    'numCode': '+1664'
  }, {
    'country': '摩洛哥',
    'numCode': '+212'
  }, {
    'country': '莫桑比克',
    'numCode': '+258'
  }, {
    'country': '缅甸',
    'numCode': '+95'
  }, {
    'country': '秘鲁',
    'numCode': '+51'
  }, {
    'country': '美属萨摩亚',
    'numCode': '+685'
  }, {
    'country': '美国',
    'numCode': '+1'
  }, {
    'country': '马其顿',
    'numCode': '+389'
  }]
}, {
  'letter': 'N',
  'data': [{
    'country': '那米比亚',
    'numCode': '+264'
  }, {
    'country': '瑙鲁',
    'numCode': '+674'
  }, {
    'country': '尼泊尔',
    'numCode': '+977'
  }, {
    'country': '尼加拉瓜',
    'numCode': '+505'
  }, {
    'country': '尼日尔',
    'numCode': '+227'
  }, {
    'country': '尼日利亚',
    'numCode': '+234'
  }, {
    'country': '诺福克岛',
    'numCode': '+6723'
  }, {
    'country': '挪威',
    'numCode': '+47'
  }, {
    'country': '南非',
    'numCode': '+27'
  }, {
    'country': '南斯拉夫',
    'numCode': '+381'
  }, {
    'country': '南奥赛梯',
    'numCode': '+7'
  }, {
    'country': '南苏丹共和国',
    'numCode': '+211'
  }]
}, {
  'letter': 'P',
  'data': [{
    'country': '皮特凯恩岛',
    'numCode': '+64'
  }, {
    'country': '葡萄牙',
    'numCode': '+351'
  }]
}, {
  'letter': 'Q',
  'data': [{
    'country': '卡塔尔',
    'numCode': '+974'
  }]
}, {
  'letter': 'R',
  'data': [{
    'country': '日本',
    'numCode': '+81'
  }, {
    'country': '瑞典',
    'numCode': '+46'
  }, {
    'country': '瑞士',
    'numCode': '+41'
  }]
}, {
  'letter': 'S',
  'data': [{
    'country': '萨摩亚',
    'numCode': '+684'
  }, {
    'country': '圣延岛',
    'numCode': '+61'
  }, {
    'country': '塞浦路斯',
    'numCode': '+357'
  }, {
    'country': '萨尔瓦多',
    'numCode': '+503'
  }, {
    'country': '圣马力诺共和国',
    'numCode': '+378'
  }, {
    'country': '沙特阿拉伯',
    'numCode': '+966'
  }, {
    'country': '塞内加尔',
    'numCode': '+221'
  }, {
    'country': '塞尔维亚共和国',
    'numCode': '+381'
  }, {
    'country': '塞舌尔',
    'numCode': '+248'
  }, {
    'country': '塞拉利昂',
    'numCode': '+232'
  }, {
    'country': '斯洛伐克（斯洛伐克人的共和国）',
    'numCode': '+421'
  }, {
    'country': '斯洛文尼亚',
    'numCode': '+386'
  }, {
    'country': '索罗门群岛',
    'numCode': '+677'
  }, {
    'country': '索马里',
    'numCode': '+252'
  }, {
    'country': '斯里兰卡',
    'numCode': '+94'
  }, {
    'country': '苏丹',
    'numCode': '+249'
  }, {
    'country': '苏里南',
    'numCode': '+597'
  }, {
    'country': '斯威士兰',
    'numCode': '+268'
  }, {
    'country': '圣基茨和尼维斯',
    'numCode': '+1869'
  }, {
    'country': '圣卢西亚岛',
    'numCode': '+1758'
  }, {
    'country': '圣文森特和格林纳丁斯',
    'numCode': '+1784'
  }, {
    'country': '圣多美和普林西比',
    'numCode': '+239'
  }, {
    'country': '圣马丁岛',
    'numCode': '+590'
  }]
}, {
  'letter': 'T',
  'data': [{
    'country': '台湾地区',
    'numCode': '+886'
  }, {
    'country': '塔吉克',
    'numCode': '+992'
  }, {
    'country': '坦桑尼亚',
    'numCode': '+255'
  }, {
    'country': '泰国',
    'numCode': '+66'
  }, {
    'country': '托克劳',
    'numCode': '+690'
  }, {
    'country': '汤加',
    'numCode': '+676'
  }, {
    'country': '特立尼达和多巴哥',
    'numCode': '+1868'
  }, {
    'country': '突尼斯',
    'numCode': '+216'
  }, {
    'country': '土耳其',
    'numCode': '+90'
  }, {
    'country': '土库曼',
    'numCode': '+993'
  }, {
    'country': '土克斯及开科斯群岛',
    'numCode': '+1809'
  }, {
    'country': '图瓦卢',
    'numCode': '+688'
  }]
}, {
  'letter': 'W',
  'data': [{
    'country': '文莱达鲁萨兰国',
    'numCode': '+673'
  }, {
    'country': '危地马拉',
    'numCode': '+502'
  }, {
    'country': '外蒙古',
    'numCode': '+976'
  }, {
    'country': '乌干达',
    'numCode': '+256'
  }, {
    'country': '乌克兰',
    'numCode': '+380'
  }, {
    'country': '乌拉圭',
    'numCode': '+598'
  }, {
    'country': '乌兹别克斯坦',
    'numCode': '+998'
  }, {
    'country': '瓦努阿图',
    'numCode': '+678'
  }, {
    'country': '委内瑞拉',
    'numCode': '+58'
  }, {
    'country': '维尔京群岛(美国)',
    'numCode': '+1340'
  }, {
    'country': '沃利斯和富图纳群岛',
    'numCode': '+681'
  }]
}, {
  'letter': 'X',
  'data': [{
    'country': '希腊',
    'numCode': '+30'
  }, {
    'country': '香港',
    'numCode': '+852'
  }, {
    'country': '匈牙利',
    'numCode': '+36'
  }, {
    'country': '新喀里多尼亚',
    'numCode': '+687'
  }, {
    'country': '新西兰',
    'numCode': '+64'
  }, {
    'country': '新加坡',
    'numCode': '+65'
  }, {
    'country': '西班牙',
    'numCode': '+34'
  }, {
    'country': '叙利亚',
    'numCode': '+963'
  }, {
    'country': '西撒哈拉',
    'numCode': '+685'
  }]
}, {
  'letter': 'Y',
  'data': [{
    'country': '亚美尼亚',
    'numCode': '+374'
  }, {
    'country': '英属印度洋领地',
    'numCode': '+246'
  }, {
    'country': '印度',
    'numCode': '+91'
  }, {
    'country': '印度尼西亚',
    'numCode': '+62'
  }, {
    'country': '伊朗（伊斯兰共和国）',
    'numCode': '+98'
  }, {
    'country': '伊拉克',
    'numCode': '+964'
  }, {
    'country': '以色列',
    'numCode': '+972'
  }, {
    'country': '意大利',
    'numCode': '+39'
  }, {
    'country': '牙买加',
    'numCode': '+1876'
  }, {
    'country': '约旦',
    'numCode': '+962'
  }, {
    'country': '英国',
    'numCode': '+44'
  }, {
    'country': '越南',
    'numCode': '+84'
  }, {
    'country': '也门',
    'numCode': '+967'
  }]
}, {
  'letter': 'Z',
  'data': [{
    'country': '中非共和国',
    'numCode': '+236'
  }, {
    'country': '乍得',
    'numCode': '+235'
  }, {
    'country': '智利',
    'numCode': '+56'
  }, {
    'country': '直布罗陀',
    'numCode': '+350'
  }, {
    'country': '朝鲜',
    'numCode': '+850'
  }, {
    'country': '赞比亚',
    'numCode': '+260'
  }, {
    'country': '泽西岛',
    'numCode': '+44'
  }, {
    'country': '中国',
    'numCode': '+86'
  }]
}]
